In [3]:
import pandas as pd
from sklearn.linear_model import LogisticRegression # our model
from sklearn.model_selection import train_test_split

In [4]:
# load my data 
car_data=pd.read_csv('./data/User_Data.csv')
car_data.sample(5)

User ID  Gender  Age  EstimatedSalary  Purchased
45   15639277    Male   23            20000          0
359  15709183    Male   42            54000          0
395  15691863  Female   46            41000          1
328  15796351    Male   36           118000          1
115  15689237    Male   40            57000          0

In [5]:
car_data.shape

(400, 5)

In [6]:
car_data.describe()


User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [7]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [10]:
# data encoding 

car_data['Gender']=car_data['Gender'].replace(to_replace={'Male':1,'Female':0})
car_data['Gender']
car_data

C:\Users\ASUS\AppData\Local\Temp\ipykernel_20056\951097432.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  car_data['Gender']=car_data['Gender'].replace(to_replace={'Male':1,'Female':0})


User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [11]:
# go for selection the data / feature selection
features=['Gender','Age','EstimatedSalary']
X=car_data[features] # independent variable /features
Y=car_data['Purchased']

In [12]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,train_size=0.8,random_state=2)

In [13]:
x_train

Gender  Age  EstimatedSalary
205       0   47            47000
354       1   36            99000
3         0   27            57000
264       1   48            90000
194       1   28            89000
..      ...  ...              ...
299       1   46           117000
22        1   48            41000
72        0   20            23000
15        1   29            80000
168       1   29           148000

[320 rows x 3 columns]

In [14]:
# feature scaling 
from sklearn.preprocessing import StandardScaler
st_sc=StandardScaler()
X_train=st_sc.fit_transform(x_train)
X_test=st_sc.fit_transform(x_test)


In [15]:
X_train

array([[-0.97530483,  0.88928823, -0.65924556],
       [ 1.02532046, -0.17254846,  0.87392651],
       [-0.97530483, -1.04132394, -0.36440478],
       [ 1.02532046,  0.98581884,  0.6085698 ],
       [ 1.02532046, -0.94479333,  0.57908572],
       [-0.97530483,  0.40663519,  0.01888824],
       [ 1.02532046,  0.98581884,  2.11225779],
       [ 1.02532046,  0.31010458, -0.30543662],
       [ 1.02532046,  1.7580637 , -0.27595254],
       [ 1.02532046, -0.17254846,  2.20071003],
       [-0.97530483,  1.7580637 ,  1.0213469 ],
       [ 1.02532046, -1.33091576, -1.48479975],
       [-0.97530483,  2.04765553,  0.54960165],
       [-0.97530483,  1.27541066,  1.90586924],
       [ 1.02532046, -1.13785454,  0.31372902],
       [-0.97530483, -0.36560968, -0.77718187],
       [ 1.02532046, -1.71703819,  0.49063349],
       [ 1.02532046, -0.5586709 , -1.51428383],
       [ 1.02532046,  0.31010458, -0.71821372],
       [-0.97530483,  0.02051275, -0.57079333],
       [ 1.02532046,  0.02051275,  0.048

In [16]:
model=LogisticRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [17]:
y_pred=model.predict(X_test)
y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [18]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("confusion matrix \n",cm)

confusion matrix 
 [[45  3]
 [13 19]]


In [19]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_pred)
print(f"the accuracy of the model that u develop is {ac} ")

the accuracy of the model that u develop is 0.8 


In [20]:
## Gender	Age	EstimatedSalary
import numpy as np

new_customers=np.array([[1,25,25000],[0,25,500],[1,43,2300]]) 
new_customers=st_sc.fit_transform(new_customers)
new_cu_pred=model.predict(new_customers)
print(f"Your customers status {new_cu_pred}")

Your customers status [0 0 1]


In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_test,y_pred) #
precision = precision_score(y_test,y_pred, pos_label=1)
recall = recall_score(y_test,y_pred, pos_label=1)
f1 = f1_score(y_test,y_pred, pos_label=1)

# Print the model performance metrics
print("Accuracy:", accuracy)  # 
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.8
Precision: 0.8636363636363636
Recall: 0.59375
F1 Score: 0.7037037037037037
